"""
Database models for SmartGrid Sentinel (simplified for MVP).
"""
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, JSON, ForeignKey, Index, Text
from sqlalchemy.dialects.postgresql import UUID, INET
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

Base = declarative_base()


class GridSubstation(Base):
    __tablename__ = 'grid_substations'
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String(255), nullable=False)
    code = Column(String(50), nullable=False)
    zone = Column(String(50))
    latitude = Column(Float)
    longitude = Column(Float)
    voltage_level_kv = Column(Integer)
    capacity_mva = Column(Float)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class GridSensor(Base):
    __tablename__ = 'grid_sensors'
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    sensor_id = Column(String(100), unique=True, nullable=False)
    substation_id = Column(String, ForeignKey('grid_substations.id'))
    sensor_type = Column(String(50))
    measurement_unit = Column(String(20))
    sampling_rate_hz = Column(Float, default=1.0)
    status = Column(String(50), default='active')
    is_critical = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class SensorReading(Base):
    __tablename__ = 'sensor_readings'
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    timestamp = Column(DateTime, index=True, default=datetime.utcnow)
    sensor_id = Column(String, ForeignKey('grid_sensors.id'))
    value = Column(Float)
    quality_indicator = Column(Float, default=1.0)
    is_anomaly = Column(Boolean, default=False)


class GridAlert(Base):
    __tablename__ = 'grid_alerts'
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    alert_type = Column(String(100))
    severity = Column(String(50))
    title = Column(String(255))
    description = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)


class Incident(Base):
    """Persisted incidents generated by the orchestrator"""
    __tablename__ = 'incidents'
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    sensor_ids = Column(Text)  # comma-separated sensor ids
    risk_label = Column(String(50))
    risk_score = Column(Float)
    explanation = Column(Text)
    recommendations = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    feedback = Column(String(50))  # true_positive, false_positive, not_reviewed
    feedback_by = Column(String(100))
    feedback_at = Column(DateTime)
    # JSON-serialized compact features used by supervised classifier
    features = Column(Text)
    # If operator provides a corrected risk label, store it here (Low/Medium/High)
    correct_label = Column(String(50))

